### ISSUE TITLE
Expo prebuild fails with new monorepo structure

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#154]
## Introduction

In a monorepo with `bun` we are supposed to only run `bun install` from the root of the monorepo and `bun` takes care of installing all packages for all workspaces: 

> run bun install from the project root to install dependencies for all workspaces.
> https://bun.sh/guides/install/workspaces

We add new packages with `bun add` from either the monorepo root, or the workspaces dirs.

To prebuild our mobile app, we run `bunx expo prebuild` from the mobile wallet workspace.

## Problem

The `prebuild` command, however, needs to run `bun install` and it runs it from the mobile wallet workspace, which goes against what I mentioned earlier. This results in the error:

```
bunx expo prebuild
✔ Created native projects | /android, /ios already created | gitignore skipped
› Using current versions instead of recommended expo@~49.0.18, react-native@0.72.6.
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using bun
> bun install
Error: bun exited with non-zero code: 1
```

<details><summary>Click for full error log</summary>

```
bunx expo prebuild
✔ Created native projects | /android, /ios already created | gitignore skipped
› Using current versions instead of recommended expo@~49.0.18, react-native@0.72.6.
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using bun
> bun install
Error: bun exited with non-zero code: 1
Error: bun exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/ilias/dev/alephium/alephium-frontend/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/Users/ilias/dev/alephium/alephium-frontend/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at BunPackageManager.runAsync (/Users/ilias/dev/alephium/alephium-frontend/node_modules/@expo/package-manager/build/node/BasePackageManager.js:38:42)
    at BunPackageManager.installAsync (/Users/ilias/dev/alephium/alephium-frontend/node_modules/@expo/package-manager/build/node/BunPackageManager.js:26:21)
    at BunPackageManager.addAsync (/Users/ilias/dev/alephium/alephium-frontend/node_modules/@expo/package-manager/build/node/BunPackageManager.js:30:25)
    at installPackagesAsync (/Users/ilias/dev/alephium/alephium-frontend/node_modules/@expo/cli/build/src/install/installAsync.js:102:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prebuildAsync (/Users/ilias/dev/alephium/alephium-frontend/node_modules/@expo/cli/build/src/prebuild/prebuildAsync.js:78:9)
```
</details>

To debug this error, I run `bun install` from the mobile wallet monorepo and I get this error:

```
bun install
bun install v1.0.12 (85c99751)


error: Duplicate dependency: "tsconfig" specified in package.json
{
^
/Users/ilias/dev/alephium/alephium-frontend/package.json:1:1 0

note: "tsconfig" originally specified here

    "tsconfig": "*",
                ^
```

### 1. Remove `"tsconfig": "*"` from the monorepo root  `package.json`

With this approach, the `bunx expo prebuild` command works again, but it creates 1 new problem and 1 concern:

#### 1. Mobile wallet typecheck fails

```
cd apps/mobile-wallet
bun typecheck
$ tsc --noEmit
src/navigation/AddressesTabNavigation.tsx:28:13 - error TS2322: Type '({ contentStyle, ...props }: BottomBarScrollScreenProps & TabBarPageProps) => React.JSX.Element | null' is not assignable to type '(props: TabBarPageProps) => ReactNode'.
  Types of parameters '__0' and 'props' are incompatible.
    Type 'TabBarPageProps' is not assignable to type 'BottomBarScrollScreenProps & TabBarPageProps'.
      Type 'TabBarPageProps' is not assignable to type 'BottomBarScrollScreenProps'.
        Types of property 'contentContainerStyle' are incompatible.
          Type 'StyleProp<AnimatedStyle<StyleProp<ViewStyle>>>' is not assignable to type 'StyleProp<ViewStyle>'.
            Type 'SharedValue<ViewStyle>' is not assignable to type 'StyleProp<ViewStyle>'.

28     pages={[AddressesScreen, ContactsScreen]}
               ~~~~~~~~~~~~~~~

src/navigation/AddressesTabNavigation.tsx:28:30 - error TS2322: Type '({ contentStyle, ...props }: BottomBarScrollScreenProps & TabBarPageProps) => React.JSX.Element' is not assignable to type '(props: TabBarPageProps) => ReactNode'.
  Types of parameters '__0' and 'props' are incompatible.
    Type 'TabBarPageProps' is not assignable to type 'BottomBarScrollScreenProps & TabBarPageProps'.

28     pages={[AddressesScreen, ContactsScreen]}
                                ~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/navigation/AddressesTabNavigation.tsx:28
```

#### 2. Not aligned with Turborepo codegen

Lastly, it's worth mentioning that removing `"tsconfig": "*",` from the monorepo root `package.json` also goes against the generated code from running `npx create-turbo@latest`, which includes a reference to the typescript config internal package in the `package.json` of the root, as well as of the workspaces:

```json
"devDependencies": {
    "@repo/eslint-config": "*",
    "@repo/typescript-config": "*",
  },
```

### 2. Configure `expo prebuild`

I tried the `--no-install` flag, but it defeats the point of prebuilding, because when packages get updated the build files won't get updated to reflect these changes.

I also tried adding a `preinstall` script to `cd ../../` or an `install` script to `cd ../../ bun install`, but that also didn't work.

Docs: https://docs.expo.dev/workflow/prebuild/

### 3. Configure `bun install`

I tried creating a `bunfig.toml` file in the mobile wallet workspace to skip installing dev dependencies, but it didn't work.

Docs: https://bun.sh/docs/cli/install#configuration

## Workaround

The only workaround I have found so far is to remove `"tsconfig": "*"` from the monorepo root  `package.json` before running `bunx expo prebuild` and put it back again without committing this change to GitHub. This is not a sustainable or a long-term solution, however.

**Comment by nop33** [comment]
What we could try is to create a reproducible example and report it to Turborepo/bun/expo for help:

1. Create a new monorepo with `npx create-turbo@latest`
2. Choose `bun` as the package manager
3. Create a new expo project as a workspace of this monorepo
4. Try to run `bunx expo prebuild`

**Comment by nop33** [comment]
We don't have this issue after moving to pnpm. Closing.
